# Generated by Django 6.0.7 on 2026-07-17 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'faculte',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('ordre', models.PositiveSmallIntegerField()),
                ('cycle', models.CharField(choices=[('LMD', 'Système LMD'), ('ING', 'Cycle Ingénieur')], default='LMD', max_length=3)),
            ],
            options={
                'db_table': 'niveau',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='classification.faculte')),
            ],
            options={
                'db_table': 'filiere',
                'ordering': ['nom'],
                'unique_together': {('nom', 'faculte')},
            },
        ),
    ]
