# Generated by Django 6.0.7 on 2026-07-17 13:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('auteur', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('memoire_licence', 'Mémoire de Licence'), ('memoire_master', 'Mémoire de Master'), ('these_doctorat', 'Thèse de Doctorat'), ('article', 'Article de recherche'), ('rapport', 'Rapport de stage')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15)),
                ('annee', models.PositiveSmallIntegerField()),
                ('resume', models.TextField(blank=True)),
                ('mots_cles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('directeur', models.CharField(blank=True, max_length=200)),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('raison_rejet', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approbations', to=settings.AUTH_USER_MODEL)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='classification.faculte')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='classification.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='classification.niveau')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-date_soumission'],
                'indexes': [models.Index(fields=['statut'], name='document_statut_3f51a5_idx'), models.Index(fields=['faculte', 'filiere', 'niveau'], name='document_faculte_ad9e9b_idx'), models.Index(fields=['annee'], name='document_annee_a5e02d_idx'), models.Index(fields=['type'], name='document_type_112a60_idx')],
            },
        ),
    ]
