import type { Document, Faculte, Niveau } from "@/types"

export const MOCK_NIVEAUX: Niveau[] = [
  { id: "n1", nom: "Licence 1", ordre: 1 },
  { id: "n2", nom: "Licence 2", ordre: 2 },
  { id: "n3", nom: "Licence 3", ordre: 3 },
  { id: "n4", nom: "Master 1", ordre: 4 },
  { id: "n5", nom: "Master 2", ordre: 5 },
  { id: "n6", nom: "Doctorat", ordre: 6 },
]

export const MOCK_FACULTES: Faculte[] = [
  {
    id: "f1", nom: "Sciences Économiques et de Gestion", code: "FASEG",
    filieres: [
      { id: "fi1", nom: "Finance islamique", faculteId: "f1" },
      { id: "fi2", nom: "Économie du développement", faculteId: "f1" },
      { id: "fi3", nom: "Commerce international", faculteId: "f1" },
    ],
  },
  {
    id: "f2", nom: "Droit", code: "FSJP",
    filieres: [
      { id: "fi4", nom: "Droit privé", faculteId: "f2" },
      { id: "fi5", nom: "Droit public", faculteId: "f2" },
      { id: "fi6", nom: "Droit islamique", faculteId: "f2" },
    ],
  },
  {
    id: "f3", nom: "Lettres et Sciences Humaines", code: "FLSH",
    filieres: [
      { id: "fi7", nom: "Philosophie", faculteId: "f3" },
      { id: "fi8", nom: "Histoire", faculteId: "f3" },
      { id: "fi9", nom: "Sociologie", faculteId: "f3" },
    ],
  },
  {
    id: "f4", nom: "Sciences de l'Éducation", code: "FASTEF",
    filieres: [
      { id: "fi10", nom: "Pédagogie", faculteId: "f4" },
      { id: "fi11", nom: "Didactique", faculteId: "f4" },
    ],
  },
  {
    id: "f5", nom: "Médecine, Pharmacie et Odontologie", code: "FMPO",
    filieres: [
      { id: "fi12", nom: "Médecine générale", faculteId: "f5" },
      { id: "fi13", nom: "Pharmacie", faculteId: "f5" },
    ],
  },
  {
    id: "f6", nom: "Sciences et Techniques", code: "FST",
    filieres: [
      { id: "fi14", nom: "Informatique", faculteId: "f6" },
      { id: "fi15", nom: "Mathématiques", faculteId: "f6" },
      { id: "fi16", nom: "Physique", faculteId: "f6" },
    ],
  },
]

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "1",
    titre: "Impact du financement islamique sur le développement économique au Sénégal",
    auteur: "Moussa Diallo",
    type: "memoire_master",
    statut: "approuve",
    faculte: "Sciences Économiques et de Gestion",
    filiere: "Finance islamique",
    niveau: "Master 2",
    annee: 2023,
    directeur: "Prof. Abdoulaye Mbaye",
    resume: "Analyse des instruments de financement islamique et leur impact sur l'inclusion financière au Sénégal. Étude des mécanismes de mourabaha, moucharaka et waqf.",
    motsCles: ["Finance islamique", "Développement économique", "Sénégal", "Waqf"],
    pages: 87,
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    soumisParId: "u1",
    soumisLe: "2023-06-15",
    approuveLe: "2023-06-20",
    approuveParId: "admin1",
  },
  {
    id: "2",
    titre: "L'éducation coranique et son intégration dans le système éducatif formel sénégalais",
    auteur: "Aïssatou Ndiaye",
    type: "these_doctorat",
    statut: "approuve",
    faculte: "Sciences de l'Éducation",
    filiere: "Pédagogie",
    niveau: "Doctorat",
    annee: 2022,
    directeur: "Prof. Mamadou Sall",
    resume: "Étude comparative entre l'enseignement traditionnel coranique (daara) et l'éducation formelle. Analyse des complémentarités et des défis d'intégration.",
    motsCles: ["Éducation coranique", "Daara", "Système éducatif", "Intégration"],
    pages: 312,
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    soumisParId: "u2",
    soumisLe: "2022-09-10",
    approuveLe: "2022-09-25",
    approuveParId: "admin1",
  },
  {
    id: "3",
    titre: "Les fondements juridiques du waqf en droit sénégalais contemporain",
    auteur: "Ibrahima Sow",
    type: "memoire_licence",
    statut: "approuve",
    faculte: "Droit",
    filiere: "Droit islamique",
    niveau: "Licence 3",
    annee: 2023,
    directeur: "Dr. Fatou Ba",
    resume: "Analyse de la place du waqf dans le droit sénégalais. Étude des textes législatifs et de la jurisprudence relative aux biens de mainmorte islamique.",
    motsCles: ["Waqf", "Droit islamique", "Sénégal", "Biens de mainmorte"],
    pages: 54,
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    soumisParId: "u3",
    soumisLe: "2023-05-01",
    approuveLe: "2023-05-10",
    approuveParId: "admin1",
  },
  {
    id: "4",
    titre: "Philosophie mouride et modernité : relecture de la pensée de Cheikh Ahmadou Bamba",
    auteur: "Serigne Touba Mbacké",
    type: "these_doctorat",
    statut: "approuve",
    faculte: "Lettres et Sciences Humaines",
    filiere: "Philosophie",
    niveau: "Doctorat",
    annee: 2021,
    directeur: "Prof. Souleymane Bachir Diagne",
    resume: "Exploration de la pensée philosophique et spirituelle de Cheikh Ahmadou Bamba. Analyse des concepts de travail, d'éducation et de résistance non-violente.",
    motsCles: ["Mouridisme", "Cheikh Ahmadou Bamba", "Philosophie", "Modernité"],
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    pages: 428,
    soumisParId: "u4",
    soumisLe: "2021-03-15",
    approuveLe: "2021-04-02",
    approuveParId: "admin1",
  },
  {
    id: "5",
    titre: "Application des algorithmes de machine learning dans le diagnostic médical",
    auteur: "Fatima Zahra Kane",
    type: "memoire_master",
    statut: "approuve",
    faculte: "Sciences et Techniques",
    filiere: "Informatique",
    niveau: "Master 2",
    annee: 2023,
    directeur: "Dr. Oumar Thiongane",
    resume: "Implémentation et évaluation d'algorithmes de classification (Random Forest, SVM, réseau de neurones) pour le diagnostic de maladies tropicales à partir de données cliniques.",
    motsCles: ["Machine learning", "Diagnostic médical", "Intelligence artificielle", "Santé"],
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    pages: 98,
    soumisParId: "u5",
    soumisLe: "2023-07-20",
    approuveLe: "2023-07-30",
    approuveParId: "admin1",
  },
  {
    id: "6",
    titre: "Microfinance et autonomisation économique des femmes en milieu rural sénégalais",
    auteur: "Rokhaya Diop",
    type: "memoire_master",
    statut: "approuve",
    faculte: "Sciences Économiques et de Gestion",
    filiere: "Économie du développement",
    niveau: "Master 1",
    annee: 2022,
    directeur: "Dr. Cheikh Tidiane Fall",
    resume: "Évaluation de l'impact des programmes de microfinance sur l'autonomisation économique et sociale des femmes dans les zones rurales du Sénégal.",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    motsCles: ["Microfinance", "Genre", "Développement rural", "Autonomisation"],
    pages: 76,
    soumisParId: "u6",
    soumisLe: "2022-11-05",
    approuveLe: "2022-11-15",
    approuveParId: "admin1",
  },
  {
    id: "7",
    titre: "Histoire des Mourides au Sénégal : de la fondation de Touba à nos jours",
    auteur: "El Hadji Mbaye",
    type: "these_doctorat",
    statut: "approuve",
    faculte: "Lettres et Sciences Humaines",
    filiere: "Histoire",
    niveau: "Doctorat",
    annee: 2020,
    directeur: "Prof. Mamadou Diouf",
    resume: "Histoire complète de la confrérie mouride depuis sa fondation par Cheikh Ahmadou Bamba en 1883 jusqu'aux développements contemporains, incluant l'expansion internationale.",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    motsCles: ["Histoire", "Mouridisme", "Touba", "Confrérie"],
    pages: 534,
    soumisParId: "u7",
    soumisLe: "2020-06-30",
    approuveLe: "2020-07-15",
    approuveParId: "admin1",
  },
  {
    id: "8",
    titre: "Le code de la famille sénégalais face aux dispositions du droit musulman",
    auteur: "Mariama Bâ Diallo",
    type: "memoire_master",
    statut: "approuve",
    faculte: "Droit",
    filiere: "Droit privé",
    niveau: "Master 2",
    annee: 2023,
    directeur: "Prof. Aminata Sow Fall",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    resume: "Analyse comparative entre le code de la famille sénégalais issu du droit civil français et les dispositions du droit musulman concernant le mariage, le divorce et l'héritage.",
    motsCles: ["Droit de la famille", "Droit islamique", "Code civil", "Mariage"],
    pages: 112,
    soumisParId: "u8",
    soumisLe: "2023-04-12",
    approuveLe: "2023-04-22",
    approuveParId: "admin1",
  },
  {
    id: "9",
    titre: "Didactique du wolof : méthodes d'enseignement de la langue nationale",
    auteur: "Pape Demba Thiam",
    type: "memoire_licence",
    statut: "approuve",
    faculte: "Sciences de l'Éducation",
    filiere: "Didactique",
    niveau: "Licence 3",
    annee: 2022,
    directeur: "Dr. Ndéye Coumba Mbodj",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    resume: "Proposition de méthodes innovantes pour l'enseignement du wolof en tant que langue nationale dans le cadre scolaire formel sénégalais.",
    motsCles: ["Wolof", "Didactique", "Langue nationale", "Enseignement"],
    pages: 63,
    soumisParId: "u9",
    soumisLe: "2022-06-05",
    approuveLe: "2022-06-15",
    approuveParId: "admin1",
  },
  {
    id: "10",
    titre: "Traitement des maladies tropicales par la phytothérapie traditionnelle sénégalaise",
    auteur: "Dr. Abdou Lahad Mbow",
    type: "these_doctorat",
    statut: "approuve",
    faculte: "Médecine, Pharmacie et Odontologie",
    filiere: "Pharmacie",
    niveau: "Doctorat",
    annee: 2021,
    directeur: "Prof. Youssou Ndour",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    resume: "Inventaire et analyse des plantes médicinales utilisées en médecine traditionnelle sénégalaise pour le traitement du paludisme, de la tuberculose et d'autres maladies tropicales.",
    motsCles: ["Phytothérapie", "Médecine traditionnelle", "Maladies tropicales", "Sénégal"],
    pages: 287,
    soumisParId: "u10",
    soumisLe: "2021-09-20",
    approuveLe: "2021-10-05",
    approuveParId: "admin1",
  },
  {
    id: "11",
    titre: "Modélisation mathématique de la propagation des épidémies en Afrique subsaharienne",
    auteur: "Thierno Oumar Barry",
    type: "memoire_master",
    statut: "approuve",
    faculte: "Sciences et Techniques",
    filiere: "Mathématiques",
    niveau: "Master 2",
    annee: 2022,
    directeur: "Dr. Seydou Traoré",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    resume: "Développement et analyse de modèles mathématiques SIR/SEIR adaptés aux spécificités épidémiologiques de l'Afrique subsaharienne, avec application au COVID-19 et au paludisme.",
    motsCles: ["Modélisation", "Épidémiologie", "Mathématiques", "Afrique subsaharienne"],
    pages: 89,
    soumisParId: "u11",
    soumisLe: "2022-03-10",
    approuveLe: "2022-03-20",
    approuveParId: "admin1",
  },
  {
    id: "13",
    titre: "L'impact de l'intelligence artificielle sur l'enseignement supérieur au Sénégal",
    auteur: "Fatou Kiné Dieng",
    type: "memoire_master",
    statut: "en_attente",
    faculte: "Sciences et Techniques",
    filiere: "Informatique",
    niveau: "Master 2",
    annee: 2024,
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    directeur: "Dr. Mamadou Diallo",
    resume: "Analyse des opportunités et défis de l'intégration de l'IA dans les universités sénégalaises.",
    motsCles: ["Intelligence artificielle", "Éducation", "Sénégal", "Innovation"],
    pages: 95,
    soumisParId: "u5",
    soumisLe: "2024-09-15",
  },
  {
    id: "14",
    titre: "Le rôle de la femme dans le développement économique selon la pensée islamique",
    auteur: "Ndèye Fatou Diop",
    type: "memoire_master",
    statut: "en_attente",
    faculte: "Sciences Économiques et de Gestion",
    filiere: "Économie du développement",
    niveau: "Master 1",
    annee: 2024,
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    directeur: "Prof. Abdoulaye Mbaye",
    resume: "Étude du rôle économique de la femme à travers les principes de l'économie islamique.",
    motsCles: ["Femme", "Développement économique", "Islam", "Émancipation"],
    pages: 78,
    soumisParId: "u6",
    soumisLe: "2024-09-18",
  },
  {
    id: "15",
    titre: "Méthodes d'enseignement du Coran dans les daara modernes au Sénégal",
    auteur: "Serigne Moustapha Guèye",
    type: "these_doctorat",
    statut: "en_attente",
    faculte: "Sciences de l'Éducation",
    filiere: "Pédagogie",
    niveau: "Doctorat",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    annee: 2024,
    directeur: "Prof. Mamadou Sall",
    resume: "Thèse sur l'évolution des méthodes pédagogiques dans les écoles coraniques sénégalaises contemporaines.",
    motsCles: ["Daara", "Éducation coranique", "Pédagogie", "Sénégal"],
    pages: 345,
    soumisParId: "u14",
    soumisLe: "2024-09-02",
  },
  {
    id: "12",
    titre: "La solidarité dans la pensée économique islamique : zakât, sadaqa et waqf",
    auteur: "Cheikh Ahmed Tidiane Sy",
    type: "memoire_master",
    statut: "approuve",
    faculte: "Sciences Économiques et de Gestion",
    filiere: "Finance islamique",
    niveau: "Master 1",
    fichierUrl: "https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf",
    annee: 2023,
    directeur: "Prof. Babacar Diagne",
    resume: "Étude des instruments de solidarité économique en islam (zakât, sadaqa, waqf) et leur potentiel pour réduire les inégalités et financer le développement dans les pays musulmans.",
    motsCles: ["Zakât", "Sadaqa", "Économie islamique", "Solidarité"],
    pages: 71,
    soumisParId: "u12",
    soumisLe: "2023-01-15",
    approuveLe: "2023-01-25",
    approuveParId: "admin1",
  },
]

export function searchDocuments(
  query: string,
  filters: { type?: string; faculte?: string; niveau?: string; filiere?: string; annee?: number } = {}
): Document[] {
  const q = query.toLowerCase().trim()

  return MOCK_DOCUMENTS.filter((doc) => {
    if (
      q &&
      !doc.titre.toLowerCase().includes(q) &&
      !doc.auteur.toLowerCase().includes(q) &&
      !doc.resume?.toLowerCase().includes(q) &&
      !doc.motsCles.some((k) => k.toLowerCase().includes(q)) &&
      !doc.faculte.toLowerCase().includes(q)
    ) return false

    if (filters.type && doc.type !== filters.type) return false
    if (filters.faculte && doc.faculte !== filters.faculte) return false
    if (filters.filiere && doc.filiere !== filters.filiere) return false
    if (filters.niveau && doc.niveau !== filters.niveau) return false
    if (filters.annee && doc.annee !== filters.annee) return false

    return true
  })
}
